package com.example.android.graphqltest.api.repository

import com.apollographql.apollo.api.Response
import com.apollographql.apollo.coroutines.await
import com.example.android.graphqltest.api.RickAndMortyApi
import com.example.android.graphqltest.api.callWrappers.ResultWrapper
import com.example.android.graphqltest.api.callWrappers.safeApiCall
import com.example.graphqlapollo.CharactersListQuery
import javax.inject.Inject
import kotlinx.coroutines.Dispatchers

class CharactersRepositoryImpl @Inject constructor(
    private val charactersApi: RickAndMortyApi
) : CharactersRepository {

    private val dispatcher = Dispatchers.Main

    override suspend fun getCharacters(): ResultWrapper<Response<CharactersListQuery.Data>> {
        return safeApiCall(dispatcher){
            charactersApi.getApolloClient().query(CharactersListQuery()).await()
            // CharactersListQuery is autogenerated
        }
    }
}